version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - backend_network
    environment:
      - MONGO_URI=mongodb+srv://opsingh861:Avenger1234@cluster0.gy80ltc.mongodb.net/BlinkLink?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=thisisblink
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend_network
    restart: unless-stopped

networks:
  backend_network:
